version: '2'
services:
   db:
        image: postgres:12
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 51515:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - safamart
   odoo:
        image: odoo:15.0
        restart: always
        ports:
                - 8149:8069
                - 8072:8072
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - ./custom-addons:/mnt/custom-addons
                - odoo-data:/var/lib/odoo
        networks:
                - safamart
#    nginx:
#         image: nginx:latest
#         ports:
#                 - 8011:80
#                 - 443:443
#         restart: always
#         depends_on:
#                 - odoo
#         volumes:
#                 - ./nginx/sites-available/:/etc/nginx/sites-available/
#         networks:
#                 - safamart
volumes:
        odoo-data:
        db-data:
networks:
        safamart:
